version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      # - /data/ssl:/opt
  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069"
    volumes:
      - /data/web:/var/lib/odoo
      - /data/config:/etc/odoo
      - /data/addons:/mnt/extra-addons
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
     # - PASSWORD_FILE=/run/secrets/postgresql_password
    #secrets:
    #  - postgresql_password
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
#      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /data/pgdata:/var/lib/postgresql/data/pgdata
    #secrets:
    #  - postgresql_password
